### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by adrcotfas**
This treats #24

### CODE REVIEW

**Comment by DeweyReed** [comment]
Since getCallState only requires permission after API 31, I think we could return false in isInTelephoneCall on API 31 or later instead of deleting the feature entirely. What do you think about it?

**Comment by adrcotfas** [comment]
Sure, be right back with the changes.  
But anyway, I wonder why was this a use case in the first place for a sound picker: playing a default sound and on a lower volume for every selected sound when in call.  

Edit:  
Actually I would leave it like this. Giving the user different functionality for different Android versions would not be a good idea and the use case is quite specific and most probably never found in practice.

**Comment by adrcotfas** [comment]
The last commit treats #26

**Comment by DeweyReed** [comment]
The UI, the features, and many codes mostly are from AOSP DeskClock's ringtone picker. It is the reason why you see a lot of edge cases.

https://android.googlesource.com/platform/packages/apps/DeskClock/+/refs/heads/master/src/com/android/deskclock/AsyncRingtonePlayer.kt

You're right. The use case rarely happens.

Thanks for your contribution! I'll fix some other bugs and release a version later.

**Pull request merged**
